language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# CI 실행 완료시 메일, 슬랙으로 알람
notifications:
  email:
    recipients:
      - dldbdud314@naver.com
  slack: w1626311096-mln267936:WnK8iUddXll8nmofEiK4zWOc

before_deploy:
  - zip -r sogyeong-cbcb *
  - mkdir -p deploy
  - mv sogyeong-cbcb.zip deploy/sogyeong-cbcb.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: sogyeong-cbcb-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: Team-SoGyeong/ChaeBunChaeBunServer #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: sogyeong-cbcb-deploy # S3 버킷
    key: sogyeong-cbcb.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: sogyeong-cbcb # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: sogyeong-cbcb-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Team-SoGyeong/ChaeBunChaeBunServer
      branch: master