spring :
  profiles :
    active : local # 기본 환경 선택
---
spring:
  profiles:
    include:
      - aws         # application-aws.yml 가져오기!
  servlet:
    multipart:        # multipart file 용량 제한
      max-file-size: 10MB
      max-request-size: 10MB

# local 환경
---
spring :
  config :
    activate :
      on-profile : local
  jpa :
    generate-ddl : false
    hibernate :
      naming :
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy : org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties :
      hibernate :
        show_sql : true
        format_sql : true  #sql 예쁘게 보기
        use_sql_comments: true
        ddl-auto : none
        dialect : org.hibernate.dialect.MariaDB53Dialect
